language: java
sudo: false 

install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dinvoker.skip=true -Djacoco.skip=true -B -V
script: 
  - mvn verify -B
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" = 'develop' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then mvn deploy -DskipTests=true -Dinvoker.skip=true -Djacoco.skip=true -Prelease-artefacts --settings .travis-m2-settings.xml -B; fi

cache:
  directories:
    - $HOME/.m2
