language: java
sudo: false 

install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dinvoker.skip=true -Djacoco.skip=true -B -V
script: 
  - mvn verify -B
after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2
